" Example Vim graphical configuration.
" Copy to ~/.gvimrc or ~/_gvimrc.

set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T                 " Hide toolbar.
set background=dark              " Background.
set lines=60 columns=400          " Window dimensions.
set guifont=Menlo\ Regular:h14
set guioptions-=r                 " Don't show right scrollbar


