install ack
install ant
install apple-gcc42
install asciidoc
install bash
install binutils
install boot2docker
install brew-cask
install chicken
install cloc
install coreutils
install ctags
install dart
install dartium
install dnsmasq
install doxygen
install elixir
install emacs
install emscripten
install erlang
install exiftool
install faac
install ffmpeg
install figlet
install findutils
install fish
install fontforge
install fop
install gcc
install gcc46
install gcc48
install gdb
install gh
install ghc
install git
install gitsh
install glfw3
install glm
install gnupg
install graphviz
install grep
install hhvm
install html2text
install htop-osx
install leiningen
install libksba
install libyaml
install llvm
install mackup
install md5sha1sum
install mercurial
install mongodb
install mono
install mp3info
install ncurses
install nginx
install normalize
install openvpn
install phantomjs
install php54-mcrypt
install php55
install php56-mcrypt
install php56-memcache
install php56-memcached
install postgresql
install python
install python3
install qcachegrind
install qt5
install r
install reattach-to-user-namespace
install redis
install rename
install rhino
install rust
install scala
install sdl
install sdl2
install sfml
install siege
install sox
install ssh-copy-id
install the_silver_searcher
install tmux
install tree
install ttfautohint
install tuntap
install valgrind
install vim
install webkit2png
install wget
install xmlstarlet
install zsh
