project_name: Settings
project_root: ~/bin/dotfiles
tabs:
  - vim: cd vim;vim
  - zsh: cd zsh;vim
  - git: cd git;vim
  - grunt: cd grunt;vim
  - tmux: cd tmux;vim
  - tmuxinator: cd tmuxinator;vim
  - scripts: cd Scripts;vim
  - shell:
