if $COLORTERM == 'gnome-terminal'
    set t_Co=256
endif
source ~/.vim/setup/rainbow.vim
silent! call pathogen#runtime_append_all_bundles()
call pathogen#infect()
Helptags
source ~/.vim/setup/basics.vim
source ~/.vim/setup/theme.vim
source ~/.vim/setup/goyo.vim
source ~/.vim/setup/keybindings.vim
source ~/.vim/setup/autocmd.vim
source ~/.vim/setup/remove_arrow_keys.vim
source ~/.vim/setup/test_runners.vim
source ~/.vim/setup/dash.vim
source ~/.vim/setup/ultisnips.vim
source ~/.vim/setup/silversearcher.vim
source ~/.vim/setup/selecta.vim
source ~/.vim/setup/vimux.vim
source ~/.vim/setup/lightline.vim
source ~/.vim/setup/calendar.vim



let g:syntastic_always_populate_loc_list = 1

