# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="clauswitt"
DISABLE_AUTO_TITLE=true
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
plugins=(cw brew github node npm osx phing rake ruby rvm heroku flow3 grunt)
fpath=(~/bin/dotfiles/zsh-completions $fpath)
source $ZSH/oh-my-zsh.sh

export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
PATH=$PATH:/usr/local/Cellar/php54/bin
PATH=$PATH:/usr/local/sbin
PATH="/usr/local/share/npm/bin:$PATH"
preexec () {  }
. ~/Scripts/z.sh
function precmd () {
  z --add "$(pwd -P)"
}

PATH=$PATH:/Users/clauswitt/.rvm/bin # Add RVM to PATH for scripting
echo "export SSH_AUTH_SOCK=$SSH_AUTH_SOCK" > ~/.auth_ssh
