# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="clauswitt"
export DISABLE_AUTO_TITLE="true"
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8
plugins=(tmux git osx cw)
fpath=(/usr/local/share/zsh-completions $fpath)

PATH="/usr/local/share/npm/bin:$PATH"
PATH="$HOME/bin:$PATH"
PATH=/usr/local/bin:$PATH:$HOME/.rvm/bin:$HOME/go/bin
export NARWHAL_ENGINE=jsc
export PATH="/usr/local/narwhal/bin:$PATH"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

source $ZSH/oh-my-zsh.sh

echo "export SSH_AUTH_SOCK=$SSH_AUTH_SOCK" > ~/.auth_ssh

bindkey -v
bindkey '^R' history-incremental-pattern-search-backward



# added by travis gem
[ -f /Users/clauswitt/.travis/travis.sh ] && source /Users/clauswitt/.travis/travis.sh
source `brew --prefix`/etc/profile.d/z.sh

PERL_MB_OPT="--install_base \"/Users/clauswitt/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/Users/clauswitt/perl5"; export PERL_MM_OPT;

