(evil-leader/set-key "oo" 'open-org-dir)
(evil-leader/set-key "oa" 'my-org-archive-done-tasks)
(evil-leader/set-key "og" 'gtd)
(evil-leader/set-key "ojo" 'journal)
(evil-leader/set-key "ot" 'org-capture)
(evil-leader/set-key "on" 'notes)
(evil-leader/set-key "oG" 'groceries)
(evil-leader/set-key "oi" 'gtd-inbox)
(evil-leader/set-key "oI" 'gtd-inbox-txt)
(evil-leader/set-key "oU" 'org-mobile-push)
(evil-leader/set-key "oD" 'org-mobile-pull)
(evil-leader/set-key "oek" 'edit-personal-keybindings)
(evil-leader/set-key "oef" 'edit-personal-funcs)
(evil-leader/set-key "of" 'ff-find-other-file)
(evil-leader/set-key "*y" 'clipboard-kill-region)
(evil-leader/set-key "*p" 'clipboard-yank)
(evil-leader/set-key "ojt" 'org-jira-todo-to-jira)
(evil-leader/set-key "ojc" 'org-jira-create-issue)
(evil-leader/set-key "ojs" 'org-jira-create-subtask)
(evil-leader/set-key "ojp" 'org-jira-get-projects)
(evil-leader/set-key "ojr" 'org-jira-refresh-issue)
(evil-leader/set-key "ojP" 'org-jira-progress-issue)
(evil-leader/set-key "ojb" 'org-jira-browse-issue)



